### ISSUE TITLE
Error when running form_mapper and the path has "dem" in the name 

### ISSUE THREAD

**Issue by jeremy-kiss** [steffilazerte/LITAP#7]
I received this error when running form_mapper:

```
SETUP
Error: There is more than one eligable fill for type dem

```

The working folder path had "dem_tiles" as one of the folder names. When I moved the working folder out of this path, form_mapper worked fine.

**Comment by steffilazerte** [comment]
Yes, the functions look for files labelled with "dem", something I can definitely adjust in the future, but for now, easiest fix is to avoid 'dem' in file names. Good catch!
